api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
        api_keys:
            apiKey:
                name: Authorization
                type: header

    # The title of the API.
    title: 'BileMo API'

    # The description of the API.
    description: 'Avec BileMo, trouvez tous les smartphones au meilleur prix !'

    # The version of the API.
    version: '1.0'

    # Set this to false if you want Webby to disappear.
    show_webby: false

    # Enable HTTP Cache system
    http_cache:
        invalidation:
            enabled: true
        public: true
    defaults:
        cache_headers:
            max_age: 0
            shared_max_age: 3600
            vary: ['Content-Type', 'Authorization', 'Origin']
