api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]

    # The title of the API.
    title: 'BileMo API'

    # The description of the API.
    description: 'Avec BileMo, trouvez tous les smartphones au meilleur prix !'

    # The version of the API.
    version: '1.0'

    # Set this to false if you want Webby to disappear.
    show_webby: false
